INSERT INTO users (full_name,is_active,email,rol_id,permissions) VALUES
	 ('Luis de leon',1,'ledr1993@gmail.com',1,'[{"id": 1, "edit": true, "name": "Configuracion general", "view": true, "create": true, "delete": true}, {"id": 2, "edit": true, "name": "Usuarios", "view": true, "create": true, "delete": true}, {"id": 3, "edit": true, "name": "Reportes", "view": true, "create": true, "delete": true}, {"id": 4, "edit": true, "name": "Facturacion", "view": true, "create": true, "delete": true}, {"id": 5, "edit": true, "name": "Inventario", "view": true, "create": true, "delete": true}, {"id": 6, "edit": true, "name": "Ventas", "view": true, "create": true, "delete": true}, {"id": 7, "edit": true, "name": "Clientes", "view": true, "create": true, "delete": true}]'),
	 ('luis operador',0,'ledr1993+cabisa1@gmail.com',4,'[{"id": 4, "edit": true, "name": "Facturacion", "view": true, "create": true, "delete": true}, {"id": 5, "edit": true, "name": "Inventario", "view": true, "create": true, "delete": true}, {"id": 6, "edit": true, "name": "Ventas", "view": true, "create": true, "delete": true}]'),
	 ('luis de leon2',1,'ledr1993+cabisa@gmail.com',4,'[{"id": 4, "edit": true, "name": "Facturacion", "view": true, "create": true, "delete": true}, {"id": 5, "edit": true, "name": "Inventario", "view": true, "create": true, "delete": true}, {"id": 6, "edit": true, "name": "Ventas", "view": true, "create": true, "delete": true}]'),
	 ('luis operador',0,'ledr1993+cabisaoperador@gmail.com',4,'[{"id": 4, "edit": true, "name": "Facturacion", "view": true, "create": true, "delete": true}, {"id": 5, "edit": true, "name": "Inventario", "view": true, "create": true, "delete": true}, {"id": 6, "edit": true, "name": "Ventas", "view": true, "create": true, "delete": true}]'),
	 ('cabisa Master',1,'ledr1993+cabisaMaster@gmail.com',1,'[{"id": 1, "edit": true, "name": "Configuracion general", "view": true, "create": true, "delete": true}, {"id": 2, "edit": false, "name": "Usuarios", "view": true, "create": true, "delete": false}, {"id": 3, "edit": true, "name": "Reportes", "view": true, "create": true, "delete": true}, {"id": 4, "edit": true, "name": "Facturacion", "view": true, "create": true, "delete": true}, {"id": 5, "edit": true, "name": "Inventario", "view": true, "create": true, "delete": true}, {"id": 6, "edit": true, "name": "Ventas", "view": true, "create": true, "delete": true}, {"id": 7, "edit": true, "name": "Clientes", "view": true, "create": true, "delete": true}]'),
	 ('luisVendedor',1,'ledr1993+cabisaVendedor1@gmail.com',2,'[{"id": 4, "edit": true, "name": "Facturacion", "view": true, "create": true, "delete": true}, {"id": 5, "edit": true, "name": "Inventario", "view": true, "create": true, "delete": true}, {"id": 6, "edit": true, "name": "Ventas", "view": true, "create": true, "delete": true}, {"id": 7, "edit": true, "name": "Clientes", "view": true, "create": true, "delete": true}]');

-- INSERT INTO users (full_name, password, email, rol_name) VALUES ('Juan Oxenden', 'l31x3q', 'joxenden0@senate.gov', 'ADMIN');
-- INSERT INTO users (full_name, password, email, rol_name) VALUES ('Patten Kryzhov', 'p0W8JRZ', 'pkryzhov1@1und1.de', 'SALES');
-- INSERT INTO users (full_name, password, email, rol_name) VALUES ('Terrence Astlett', 'Df7tbQyXm', 'tastlett2@businessweek.com', 'WAREHOUSE');
-- INSERT INTO users (full_name, password, email, rol_name) VALUES ('Gregor Rouchy', 'KDJmwkeuk0dN', 'grouchy3@globo.com', 'OPERATOR');
-- INSERT INTO users (full_name, password, email, rol_name) VALUES ('Aldus Quirke', '8OclsznKdURc', 'aquirke4@wix.com', 'ADMIN');
-- INSERT INTO users (full_name, password, email, rol_name) VALUES ('Flss Pelos', 'gzgYOAXO9', 'fpelos5@intel.com', 'SALES');
-- INSERT INTO users (full_name, password, email, rol_name) VALUES ('Sidonnie Stillman', 'vhP0HpwH', 'sstillman6@blogspot.com', 'WAREHOUSE');
-- INSERT INTO users (full_name, password, email, rol_name) VALUES ('Daryl Shegog', 'EL2RWyQHRC1', 'dshegog7@aboutads.info', 'OPERATOR');