INSERT INTO roles (name,is_active) VALUES
	 ('ADMIN',1),
	 ('SELLS',1),
	 ('WAREHOUSE',1),
	 ('OPERATOR',1);

-- INSERT INTO roles
-- VALUES ('ADMIN', 'ACTIVE', '[
--   "STAKEHOLDER_CREATE",
--   "STAKEHOLDER_DELETE",
--   "STAKEHOLDER_READ",
--   "STAKEHOLDER_UPDATE",
--   "INVENTORY_CREATE",
--   "INVENTORY_DELETE",
--   "INVENTORY_READ",
--   "INVENTORY_UPDATE",
--   "INVOICE_CREATE",
--   "INVOICE_DELETE",
--   "INVOICE_READ",
--   "INVOICE_UPDATE",
--   "REPORT_CREATE",
--   "REPORT_DELETE",
--   "REPORT_READ",
--   "REPORT_UPDATE",
--   "SELL_CREATE",
--   "SELL_DELETE",
--   "SELL_READ",
--   "SELL_UPDATE",
--   "USER_CREATE",
--   "USER_DELETE",
--   "USER_READ",
--   "USER_UPDATE"
-- ]');

-- INSERT INTO roles
-- VALUES ('SALES', 'ACTIVE', '[
--   "CLIENT_CREATE",
--   "CLIENT_DELETE",
--   "CLIENT_READ",
--   "CLIENT_UPDATE",
--   "INVENTORY_CREATE",
--   "INVENTORY_DELETE",
--   "INVENTORY_READ",
--   "INVENTORY_UPDATE",
--   "INVOICE_CREATE",
--   "INVOICE_DELETE",
--   "INVOICE_READ",
--   "INVOICE_UPDATE",
--   "SELL_CREATE",
--   "SELL_DELETE",
--   "SELL_READ",
--   "SELL_UPDATE"
-- ]');

-- INSERT INTO roles
-- VALUES ('WAREHOUSE', 'ACTIVE', '[
--   "INVENTORY_CREATE",
--   "INVENTORY_DELETE",
--   "INVENTORY_READ",
--   "INVENTORY_UPDATE",
--   "INVOICE_CREATE",
--   "INVOICE_DELETE",
--   "INVOICE_READ",
--   "INVOICE_UPDATE",
--   "SELL_CREATE",
--   "SELL_DELETE",
--   "SELL_READ",
--   "SELL_UPDATE"
-- ]');

-- INSERT INTO roles
-- VALUES ('OPERATOR', 'ACTIVE', '[
--   "INVENTORY_CREATE",
--   "INVENTORY_DELETE",
--   "INVENTORY_READ",
--   "INVENTORY_UPDATE",
--   "INVOICE_CREATE",
--   "INVOICE_DELETE",
--   "INVOICE_READ",
--   "INVOICE_UPDATE",
--   "SELL_CREATE",
--   "SELL_DELETE",
--   "SELL_READ",
--   "SELL_UPDATE"
-- ]');