service: cabisa-layers

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  profile: cabisa

custom:
  config: ../envs/credentials.${self:provider.stage}.json

layers:
  nodejs:
    name: cabisa-${self:provider.stage}-layer-nodejs
    path: ../layers
    compatibleRuntimes:
      - nodejs12.x

resources:
  Outputs:
    NodejsLayerExport:
      Value:
        Ref: NodejsLambdaLayer
      Export:
        Name: NodejsLambdaLayer
