service: ca-invoice

plugins:
  - serverless-offline

custom:
  config: ../../envs/credentials.${self:provider.stage}.json

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  deploymentBucket:
    name: ${file(${self:custom.config}):deploymentBucket}
  environment:
    STAGE: ${file(${self:custom.config}):stage}
    ACCOUNT_ID: ${file(${self:custom.config}):awsAccountId}
    FILE_ENVIRONMENT: ${file(${self:custom.config}):fileEnvironment}
    RUN_LIKE: ${file(${self:custom.config}):run_like}
    DATABASE_HOST: ${file(${self:custom.config}):dbHost}
    DATABASE_USER: ${file(${self:custom.config}):dbUser}
    DATABASE_NAME: ${file(${self:custom.config}):dbName}
    DATABASE_PASSWORD: ${file(${self:custom.config}):dbPassword}
    ENCRYPTION_KEY: ${file(${self:custom.config}):encryptionKey}

package:
  exclude:
    - node_modules/**
  include:
    - ../../globals/**
functions:
  invoicesCreate:
    handler: handler.create
    timeout: 30
    events:
      - http:
          path: invoicefel/create
          method: post
          cors:
            origin: '*'
            allowCredentials: true
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
    layers:
      - arn:${file(${self:custom.config}):layer}