service: ca-products

plugins:
  - serverless-offline

custom:
  config: ../../envs/credentials.${self:provider.stage}.json

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'prod'}
  region: us-east-1
  deploymentBucket:
    name: ${file(${self:custom.config}):deploymentBucket}
  environment:
    STAGE: ${file(${self:custom.config}):stage}
    ACCOUNT_ID: ${file(${self:custom.config}):awsAccountId}
    FILE_ENVIRONMENT: ${file(${self:custom.config}):fileEnvironment}
    RUN_LIKE: ${file(${self:custom.config}):run_like}
    DATABASE_HOST: ${file(${self:custom.config}):dbHost}
    DATABASE_USER: ${file(${self:custom.config}):dbUser}
    DATABASE_NAME: ${file(${self:custom.config}):dbName}
    DATABASE_PASSWORD: ${file(${self:custom.config}):dbPassword}

package:
  exclude:
    - node_modules/**
  include:
    - ../../globals/**
functions:
  products:
    handler: handler.read
    events:
      - http:
          path: products
          method: get
          cors: true
    layers:
      - arn:${file(${self:custom.config}):layer}

  productsCategories:
    handler: handler.readProductsCategories
    events:
      - http:
          path: products-categories
          method: get
          cors: true
    layers:
      - arn:${file(${self:custom.config}):layer}

  productsStatus:
    handler: handler.readProductsStatus
    events:
      - http:
          path: products-status
          method: get
          cors: true
    layers:
      - arn:${file(${self:custom.config}):layer}

  productsTaxes:
    handler: handler.readProductTaxes
    events:
      - http:
          path: products-taxes
          method: get
          cors: true
    layers:
      - arn:${file(${self:custom.config}):layer}

  productsOptions:
    handler: handler.readProductsOptions
    events:
      - http:
          path: products-options
          method: get
          cors: true
    layers:
      - arn:${file(${self:custom.config}):layer}

  productsCreate:
    handler: handler.create
    events:
      - http:
          path: products
          method: post
          cors: true
    layers:
      - arn:${file(${self:custom.config}):layer}

  productsUpdate:
    handler: handler.update
    events:
      - http:
          path: products
          method: put
          cors: true
    layers:
      - arn:${file(${self:custom.config}):layer}

  productsDelete:
    handler: handler.delete
    events:
      - http:
          path: products
          method: delete
          cors: true
    layers:
      - arn:${file(${self:custom.config}):layer}
