CREATE TABLE `products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_type` ENUM('SERVICE','PRODUCT') CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `product_category` ENUM('EQUIPMENT','PART') CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `status` ENUM('ACTIVE','INACTIVE','BLOCKED') CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT 'ACTIVE' NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `code` VARCHAR(50) NOT NULL,
  `serial_number` VARCHAR(50) DEFAULT NULL,
  `unit_price` DOUBLE NOT NULL DEFAULT 0,
  `tax_id` INT DEFAULT NULL,
  `stock` INT DEFAULT 0 NOT NULL,
  `inventory_unit_value` DOUBLE DEFAULT 0 NOT NULL,
  `inventory_total_value` DOUBLE DEFAULT 0 NOT NULL,
  `image_url` TEXT DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` INT NOT NULL,
  `updated_at` TIMESTAMP ON UPDATE CURRENT_TIMESTAMP DEFAULT NULL,
  `updated_by` INT,
  CONSTRAINT products_pk PRIMARY KEY (`id`),
  CONSTRAINT products_created_by_fk FOREIGN KEY (created_by) REFERENCES users(id),
  CONSTRAINT products_updated_by_fk FOREIGN KEY (updated_by) REFERENCES users(id),
  CONSTRAINT products_product_category_check CHECK (product_type <> 'PRODUCT' OR product_category IS NOT NULL),
  CONSTRAINT products_code_product_type_unique UNIQUE (code, product_type, product_category)
) ENGINE=InnoDB;