service: ca-users

plugins:
  - serverless-offline

custom:
  config: ../../envs/credentials.${self:provider.stage}.json

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  deploymentBucket:
    name: ${file(${self:custom.config}):deploymentBucket}
  environment:
    STAGE: ${file(${self:custom.config}):stage}
    ACCOUNT_ID: ${file(${self:custom.config}):awsAccountId}
    FILE_ENVIRONMENT: ${file(${self:custom.config}):fileEnvironment}
    RUN_LIKE: ${file(${self:custom.config}):run_like}
    DATABASE_HOST: ${file(${self:custom.config}):dbHost}
    DATABASE_USER: ${file(${self:custom.config}):dbUser}
    DATABASE_NAME: ${file(${self:custom.config}):dbName}
    DATABASE_PASSWORD: ${file(${self:custom.config}):dbPassword}
    ENCRYPTION_KEY: ${file(${self:custom.config}):encryptionKey}

package:
  exclude:
    - node_modules/**
  include:
    - ../../globals/**
functions:
  users:
    handler: handler.read
    events:
      - http:
          path: users
          method: get
          cors: true
    layers:
      - arn:${file(${self:custom.config}):layer}

  roles:
    handler: handler.readRoles
    events:
      - http:
          path: users/roles
          method: get
          cors: true
    layers:
      - arn:${file(${self:custom.config}):layer}

  usersCreate:
    handler: handler.create
    events:
      - http:
          path: users
          method: post
          cors: true
    layers:
      - arn:${file(${self:custom.config}):layer}

  usersUpdate:
    handler: handler.update
    events:
      - http:
          path: users
          method: put
          cors: true
    layers:
      - arn:${file(${self:custom.config}):layer}

  permissionsUpdate:
    handler: handler.updatePermissions
    events:
      - http:
          path: users/permissions
          method: put
          cors: true
    layers:
      - arn:${file(${self:custom.config}):layer}

  usersDelete:
    handler: handler.delete
    events:
      - http:
          path: users
          method: delete
          cors: true
    layers:
      - arn:${file(${self:custom.config}):layer}

  usersPasswordChange:
    handler: handler.changePassword
    events:
      - http:
          path: users-change-password
          method: put
          cors: true
    layers:
      - arn:${file(${self:custom.config}):layer}
