service: ca-repairs

plugins:
  - serverless-offline

custom:
  config: ../../envs/credentials.${self:provider.stage}.json

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'prod'}
  region: us-east-1
  deploymentBucket:
    name: ${file(${self:custom.config}):deploymentBucket}
  environment:
    STAGE: ${file(${self:custom.config}):stage}
    ACCOUNT_ID: ${file(${self:custom.config}):awsAccountId}
    FILE_ENVIRONMENT: ${file(${self:custom.config}):fileEnvironment}
    RUN_LIKE: ${file(${self:custom.config}):run_like}
    DATABASE_HOST: ${file(${self:custom.config}):dbHost}
    DATABASE_USER: ${file(${self:custom.config}):dbUser}
    DATABASE_NAME: ${file(${self:custom.config}):dbName}
    DATABASE_PASSWORD: ${file(${self:custom.config}):dbPassword}

package:
  exclude:
    - node_modules/**
  include:
    - ../../globals/**
functions:
  repairs:
    handler: handler.read
    events:
      - http:
          path: repairs
          method: get
          cors: true
    layers:
      - arn:${file(${self:custom.config}):layer}

  repairsStatus:
    handler: handler.readRepairsStatus
    events:
      - http:
          path: repairs-status
          method: get
          cors: true
    layers:
      - arn:${file(${self:custom.config}):layer}

  repairsCreate:
    handler: handler.create
    events:
      - http:
          path: repairs
          method: post
          cors: true
    layers:
      - arn:${file(${self:custom.config}):layer}

  repairsApprove:
    handler: handler.approve
    events:
      - http:
          path: repairs/approve
          method: put
          cors: true
    layers:
      - arn:${file(${self:custom.config}):layer}

  repairsUpdate:
    handler: handler.update
    events:
      - http:
          path: repairs
          method: put
          cors: true
    layers:
      - arn:${file(${self:custom.config}):layer}

  repairsCancel:
    handler: handler.cancel
    events:
      - http:
          path: repairs/cancel
          method: put
          cors: true
    layers:
      - arn:${file(${self:custom.config}):layer}
